### ISSUE TITLE
Fix CI test problems

### ISSUE THREAD

**Issue by io7m** [io7m-com/jcoronado#16]
On Linux containers:

```
2024-05-03T11:51:27.4712292Z [ERROR] com.io7m.jcoronado.tests.device.VulkanLWJGLLogicalDeviceTest.testCreateBuffer -- Time elapsed: 0.002 s <<< ERROR!
2024-05-03T11:51:27.4714909Z java.lang.IllegalStateException: com.io7m.jcoronado.api.VulkanCallFailedException: Function vkCreateInstance returned 0xfffffffa (-6) (VK_ERROR_LAYER_NOT_PRESENT)
2024-05-03T11:51:27.4717221Z 	at com.io7m.jcoronado.tests.device.VulkanLWJGLLogicalDeviceTest.createInstance(VulkanLWJGLLogicalDeviceTest.java:74)
2024-05-03T11:51:27.4719390Z 	at com.io7m.jcoronado.tests.device.VulkanLWJGLLogicalDeviceTest.createPhysicalDevice(VulkanLWJGLLogicalDeviceTest.java:100)
2024-05-03T11:51:27.4721546Z 	at com.io7m.jcoronado.tests.contracts.VulkanLogicalDeviceContract.testSetup(VulkanLogicalDeviceContract.java:142)
2024-05-03T11:51:27.4723056Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
2024-05-03T11:51:27.4724018Z 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
2024-05-03T11:51:27.4724980Z 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
```

On Windows containers:

```
2024-05-03T11:52:28.4963446Z [ERROR] com.io7m.jcoronado.tests.device.VulkanLWJGLLogicalDeviceTest.testCreateLogicalDeviceWithFeaturesHighest -- Time elapsed: 0.015 s <<< ERROR!
2024-05-03T11:52:28.4965435Z java.lang.NoClassDefFoundError: Could not initialize class org.lwjgl.vulkan.VK
2024-05-03T11:52:28.4966517Z 	at org.lwjgl.vulkan.VK10.nvkCreateInstance(VK10.java:2706)
2024-05-03T11:52:28.4967435Z 	at org.lwjgl.vulkan.VK10.vkCreateInstance(VK10.java:2776)
2024-05-03T11:52:28.4968848Z 	at com.io7m.jcoronado.lwjgl.VulkanLWJGLInstanceProvider.createInstance(VulkanLWJGLInstanceProvider.java:265)
2024-05-03T11:52:28.4970894Z 	at com.io7m.jcoronado.tests.device.VulkanLWJGLLogicalDeviceTest.createInstance(VulkanLWJGLLogicalDeviceTest.java:72)
2024-05-03T11:52:28.4973078Z 	at com.io7m.jcoronado.tests.device.VulkanLWJGLLogicalDeviceTest.createPhysicalDevice(VulkanLWJGLLogicalDeviceTest.java:100)
2024-05-03T11:52:28.4975221Z 	at com.io7m.jcoronado.tests.contracts.VulkanLogicalDeviceContract.testSetup(VulkanLogicalDeviceContract.java:142)
2024-05-03T11:52:28.4976708Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
2024-05-03T11:52:28.4977649Z 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
2024-05-03T11:52:28.4978575Z 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
```

It might just be impossible to run these tests on Windows on GH CI.

**Comment by io7m** [comment]
Seems like all that was necessary was to actually install a Vulkan SDK.
